# These settings are synced to GitHub by https://github.com/marketplace/actions/repository-settings-action

repository:
  description: GitHub Action for managing repo settings as code
  homepage: https://github.com/marketplace/actions/repository-settings-action
  topics:
    - github-actions
    - typescript
  has_issues: true
  has_projects: true
  has_wiki: true
  has_discussions: true
  is_template: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true

#teams:
#  - name: org/team-1
#    permission: push
#  - name: team-2
#    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - Check dist/
          - TypeScript Tests
      enforce_admins: true
      required_linear_history: true
      restrictions: null
