name: Repository Settings Action
description: GitHub Actions wrapper for the repository-settings/app Probot app

branding:
  icon: settings
  color: orange

runs:
  using: node20
  main: dist/index.js
