# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Repository Settings Action
description: GitHub Action to manage repository settings as code
author: Kyle Johnson

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'settings'
  color: 'orange'

# Define your inputs here.
inputs:
  token:
    description: The GitHub token to use for authentication
    required: true
  settings-path:
    description: The path to the settings file
    default: '.github/settings.yml'

runs:
  using: node20
  main: dist/index.js
